spring:
  application:
    name: employee-management

  datasource:
    urL: jdbc:postgresql://localhost:5432/employee_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update              # Cria/atualiza tabelas automaticamente
    show-sql: true                  # Mostra as queries no console (útil para aprender)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # CORS para conectar com o frontend React
  mvc:
    cors:
      allowed-origins: http://localhost:5173

server:
  port:8080
